- name: Hashnode Blog
  uses: varunsridharan/action-hashnode-blog@1.1.1
    with:
      USERNAME: 'dapoadedire'
      COUNT: 5
      STYLE: "list"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
